### ISSUE TITLE
Dafny installation not working properly on MacOS

### ISSUE THREAD

**Issue by pipeaesac** [DafnyVSCode/VS-Code-Language-Server-for-Dafny#6]
When installing the plugin in VSCode, a message indicates that in order for the plugin to work, Dafny has to be installed. When accepting the prompt to install, VSCode starts the installation. Then, after an apparently successful installation, the prompt reappears.

**Comment by pipeaesac** [comment]
I am using macOS Sierra (Version 10.12.6)

**Comment by kevinsullivan** [comment]
Be sure that Mono is installed before installing Dafny.

**Comment by pipeaesac** [comment]
That was exactly the problem. Thank you Kevin.
